/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE_API__system
#define __PYX_HAVE_API__system
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"
#include "system.h"

static void (*__pyx_api_f_6system_restoreErrorHandler)(void) = 0;
#define restoreErrorHandler __pyx_api_f_6system_restoreErrorHandler
static PyObject *(*__pyx_api_f_6system_popLastErrorMessage)(void) = 0;
#define popLastErrorMessage __pyx_api_f_6system_popLastErrorMessage
static sf::String (*__pyx_api_f_6system_to_string)(PyObject *) = 0;
#define to_string __pyx_api_f_6system_to_string
static PyObject *(*__pyx_api_f_6system_wrap_string)(sf::String const *) = 0;
#define wrap_string __pyx_api_f_6system_wrap_string
static struct PyVector2Object *(*__pyx_api_f_6system_wrap_vector2)(sf::Vector2<NumericObject>  *) = 0;
#define wrap_vector2 __pyx_api_f_6system_wrap_vector2
static PyObject *(*__pyx_api_f_6system_wrap_vector2i)(sf::Vector2i) = 0;
#define wrap_vector2i __pyx_api_f_6system_wrap_vector2i
static PyObject *(*__pyx_api_f_6system_wrap_vector2u)(sf::Vector2u) = 0;
#define wrap_vector2u __pyx_api_f_6system_wrap_vector2u
static PyObject *(*__pyx_api_f_6system_wrap_vector2f)(sf::Vector2f) = 0;
#define wrap_vector2f __pyx_api_f_6system_wrap_vector2f
static sf::Vector2i (*__pyx_api_f_6system_to_vector2i)(PyObject *) = 0;
#define to_vector2i __pyx_api_f_6system_to_vector2i
static sf::Vector2u (*__pyx_api_f_6system_to_vector2u)(PyObject *) = 0;
#define to_vector2u __pyx_api_f_6system_to_vector2u
static sf::Vector2f (*__pyx_api_f_6system_to_vector2f)(PyObject *) = 0;
#define to_vector2f __pyx_api_f_6system_to_vector2f
static PyObject *(*__pyx_api_f_6system_wrap_vector3)(sf::Vector3<NumericObject>  *) = 0;
#define wrap_vector3 __pyx_api_f_6system_wrap_vector3
static PyObject *(*__pyx_api_f_6system_wrap_vector3i)(sf::Vector3i) = 0;
#define wrap_vector3i __pyx_api_f_6system_wrap_vector3i
static PyObject *(*__pyx_api_f_6system_wrap_vector3f)(sf::Vector3f) = 0;
#define wrap_vector3f __pyx_api_f_6system_wrap_vector3f
static sf::Vector3i (*__pyx_api_f_6system_to_vector3i)(PyObject *) = 0;
#define to_vector3i __pyx_api_f_6system_to_vector3i
static sf::Vector3f (*__pyx_api_f_6system_to_vector3f)(PyObject *) = 0;
#define to_vector3f __pyx_api_f_6system_to_vector3f
static PyObject *(*__pyx_api_f_6system_wrap_time)(sf::Time *) = 0;
#define wrap_time __pyx_api_f_6system_wrap_time
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
#if PY_VERSION_HEX >= 0x02070000
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
#else
    {const char *desc, *s1, *s2;
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);}
#endif
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_system(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("system");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "restoreErrorHandler", (void (**)(void))&__pyx_api_f_6system_restoreErrorHandler, "void (void)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "popLastErrorMessage", (void (**)(void))&__pyx_api_f_6system_popLastErrorMessage, "PyObject *(void)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "to_string", (void (**)(void))&__pyx_api_f_6system_to_string, "sf::String (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_string", (void (**)(void))&__pyx_api_f_6system_wrap_string, "PyObject *(sf::String const *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_vector2", (void (**)(void))&__pyx_api_f_6system_wrap_vector2, "struct PyVector2Object *(sf::Vector2<NumericObject>  *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_vector2i", (void (**)(void))&__pyx_api_f_6system_wrap_vector2i, "PyObject *(sf::Vector2i)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_vector2u", (void (**)(void))&__pyx_api_f_6system_wrap_vector2u, "PyObject *(sf::Vector2u)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_vector2f", (void (**)(void))&__pyx_api_f_6system_wrap_vector2f, "PyObject *(sf::Vector2f)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "to_vector2i", (void (**)(void))&__pyx_api_f_6system_to_vector2i, "sf::Vector2i (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "to_vector2u", (void (**)(void))&__pyx_api_f_6system_to_vector2u, "sf::Vector2u (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "to_vector2f", (void (**)(void))&__pyx_api_f_6system_to_vector2f, "sf::Vector2f (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_vector3", (void (**)(void))&__pyx_api_f_6system_wrap_vector3, "PyObject *(sf::Vector3<NumericObject>  *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_vector3i", (void (**)(void))&__pyx_api_f_6system_wrap_vector3i, "PyObject *(sf::Vector3i)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_vector3f", (void (**)(void))&__pyx_api_f_6system_wrap_vector3f, "PyObject *(sf::Vector3f)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "to_vector3i", (void (**)(void))&__pyx_api_f_6system_to_vector3i, "sf::Vector3i (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "to_vector3f", (void (**)(void))&__pyx_api_f_6system_to_vector3f, "sf::Vector3f (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_time", (void (**)(void))&__pyx_api_f_6system_wrap_time, "PyObject *(sf::Time *)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__system */
