/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__audio
#define __PYX_HAVE__audio

#include "Python.h"
struct PyChunkObject;

/* "audio.pyx":77
 *         sf.listener.setUpVector(to_vector3f(up_vector))
 * 
 * cdef public class Chunk[type PyChunkType, object PyChunkObject]:             # <<<<<<<<<<<<<<
 *     cdef Int16* m_samples
 *     cdef size_t m_sampleCount
 */
struct PyChunkObject {
  PyObject_HEAD
  sf::Int16 *m_samples;
  size_t m_sampleCount;
  int delete_this;
};

#ifndef __PYX_HAVE_API__audio

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyChunkType;

#endif /* !__PYX_HAVE_API__audio */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initaudio(void);
#else
PyMODINIT_FUNC PyInit_audio(void);
#endif

#endif /* !__PYX_HAVE__audio */
