/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__window
#define __PYX_HAVE__window

#include "Python.h"
struct PyEventObject;
struct PyVideoModeObject;
struct PyContextSettingsObject;
struct PyWindowObject;

/* "window.pyx":534
 * 
 * 
 * cdef public class Event[type PyEventType, object PyEventObject]:             # <<<<<<<<<<<<<<
 *     cdef sf.Event *p_this
 *     cdef object data
 */
struct PyEventObject {
  PyObject_HEAD
  sf::Event *p_this;
  PyObject *data;
};

/* "window.pyx":689
 *     return event
 * 
 * cdef public class VideoMode[type PyVideoModeType, object PyVideoModeObject]:             # <<<<<<<<<<<<<<
 *     cdef sf.VideoMode *p_this
 *     cdef bint delete_this
 */
struct PyVideoModeObject {
  PyObject_HEAD
  sf::VideoMode *p_this;
  int delete_this;
};

/* "window.pyx":783
 *     DEBUG = sf.contextsettings.Debug
 * 
 * cdef public class ContextSettings[type PyContextSettingsType, object PyContextSettingsObject]:             # <<<<<<<<<<<<<<
 *     cdef sf.ContextSettings *p_this
 * 
 */
struct PyContextSettingsObject {
  PyObject_HEAD
  sf::ContextSettings *p_this;
};

/* "window.pyx":846
 * 
 * 
 * cdef public class Window[type PyWindowType, object PyWindowObject]:             # <<<<<<<<<<<<<<
 *     cdef sf.Window *p_window
 * 
 */
struct PyWindowObject {
  PyObject_HEAD
  sf::Window *p_window;
};

#ifndef __PYX_HAVE_API__window

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyEventType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyVideoModeType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyContextSettingsType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyWindowType;

#endif /* !__PYX_HAVE_API__window */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initwindow(void);
#else
PyMODINIT_FUNC PyInit_window(void);
#endif

#endif /* !__PYX_HAVE__window */
