/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE_API__graphics
#define __PYX_HAVE_API__graphics
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"
#include "graphics.h"

static struct PyRectObject *(*__pyx_api_f_8graphics_wrap_rect)(sf::Rect<NumericObject>  *) = 0;
#define wrap_rect __pyx_api_f_8graphics_wrap_rect
static struct PyRectObject *(*__pyx_api_f_8graphics_wrap_intrect)(sf::IntRect *) = 0;
#define wrap_intrect __pyx_api_f_8graphics_wrap_intrect
static struct PyRectObject *(*__pyx_api_f_8graphics_wrap_floatrect)(sf::FloatRect *) = 0;
#define wrap_floatrect __pyx_api_f_8graphics_wrap_floatrect
static sf::FloatRect (*__pyx_api_f_8graphics_to_floatrect)(PyObject *) = 0;
#define to_floatrect __pyx_api_f_8graphics_to_floatrect
static sf::IntRect (*__pyx_api_f_8graphics_to_intrect)(PyObject *) = 0;
#define to_intrect __pyx_api_f_8graphics_to_intrect
static struct PyColorObject *(*__pyx_api_f_8graphics_wrap_color)(sf::Color *) = 0;
#define wrap_color __pyx_api_f_8graphics_wrap_color
static struct PyBlendModeObject *(*__pyx_api_f_8graphics_wrap_blendmode)(sf::BlendMode *) = 0;
#define wrap_blendmode __pyx_api_f_8graphics_wrap_blendmode
static struct PyImageObject *(*__pyx_api_f_8graphics_wrap_image)(sf::Image *) = 0;
#define wrap_image __pyx_api_f_8graphics_wrap_image
static struct PyTextureObject *(*__pyx_api_f_8graphics_wrap_texture)(sf::Texture *, int) = 0;
#define wrap_texture __pyx_api_f_8graphics_wrap_texture
static struct PyRenderStatesObject *(*__pyx_api_f_8graphics_wrap_renderstates)(sf::RenderStates *, int) = 0;
#define wrap_renderstates __pyx_api_f_8graphics_wrap_renderstates
static PyObject *(*__pyx_api_f_8graphics_wrap_convexshape)(sf::ConvexShape *) = 0;
#define wrap_convexshape __pyx_api_f_8graphics_wrap_convexshape
static PyObject *(*__pyx_api_f_8graphics_wrap_rendertarget)(sf::RenderTarget *) = 0;
#define wrap_rendertarget __pyx_api_f_8graphics_wrap_rendertarget
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
#if PY_VERSION_HEX >= 0x02070000
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
#else
    {const char *desc, *s1, *s2;
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);}
#endif
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_graphics(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("graphics");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_rect", (void (**)(void))&__pyx_api_f_8graphics_wrap_rect, "struct PyRectObject *(sf::Rect<NumericObject>  *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_intrect", (void (**)(void))&__pyx_api_f_8graphics_wrap_intrect, "struct PyRectObject *(sf::IntRect *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_floatrect", (void (**)(void))&__pyx_api_f_8graphics_wrap_floatrect, "struct PyRectObject *(sf::FloatRect *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "to_floatrect", (void (**)(void))&__pyx_api_f_8graphics_to_floatrect, "sf::FloatRect (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "to_intrect", (void (**)(void))&__pyx_api_f_8graphics_to_intrect, "sf::IntRect (PyObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_color", (void (**)(void))&__pyx_api_f_8graphics_wrap_color, "struct PyColorObject *(sf::Color *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_blendmode", (void (**)(void))&__pyx_api_f_8graphics_wrap_blendmode, "struct PyBlendModeObject *(sf::BlendMode *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_image", (void (**)(void))&__pyx_api_f_8graphics_wrap_image, "struct PyImageObject *(sf::Image *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_texture", (void (**)(void))&__pyx_api_f_8graphics_wrap_texture, "struct PyTextureObject *(sf::Texture *, int)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_renderstates", (void (**)(void))&__pyx_api_f_8graphics_wrap_renderstates, "struct PyRenderStatesObject *(sf::RenderStates *, int)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_convexshape", (void (**)(void))&__pyx_api_f_8graphics_wrap_convexshape, "PyObject *(sf::ConvexShape *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "wrap_rendertarget", (void (**)(void))&__pyx_api_f_8graphics_wrap_rendertarget, "PyObject *(sf::RenderTarget *)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__graphics */
